// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNBjbJJ-bBi0kwX6iW2zwJA5UfHjKWZQ',
    appId: '1:65970955168:web:633f27c23b3073145cbac5',
    messagingSenderId: '65970955168',
    projectId: 'demo4-f9a7a',
    authDomain: 'demo4-f9a7a.firebaseapp.com',
    storageBucket: 'demo4-f9a7a.appspot.com',
    measurementId: 'G-81821YSJ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ZCbmt-DmbHtjBywMgv5pbSjm9cZ0wSE',
    appId: '1:65970955168:android:5dc60919b5e2f9f35cbac5',
    messagingSenderId: '65970955168',
    projectId: 'demo4-f9a7a',
    storageBucket: 'demo4-f9a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNyVxbmqIV1Hw_7UzNEFIFNdGDC0PcSU',
    appId: '1:65970955168:ios:8c16d0f15d924eba5cbac5',
    messagingSenderId: '65970955168',
    projectId: 'demo4-f9a7a',
    storageBucket: 'demo4-f9a7a.appspot.com',
    iosBundleId: 'com.example.demo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNyVxbmqIV1Hw_7UzNEFIFNdGDC0PcSU',
    appId: '1:65970955168:ios:7c92a1fc77175c5c5cbac5',
    messagingSenderId: '65970955168',
    projectId: 'demo4-f9a7a',
    storageBucket: 'demo4-f9a7a.appspot.com',
    iosBundleId: 'com.example.demo4.RunnerTests',
  );
}
